### ISSUE TITLE
[Feature Request] Logging

### ISSUE THREAD

**Issue by x3l51** [LoranKloeze/WhatsAllApp#57]
Great work! It'd be great to log when someone comes online. Cheers!

**Comment by muskw** [comment]
This is easy.

Go to [MainContent.js](https://github.com/LoranKloeze/WhatsAllApp/blob/master/src/pack/Components/MainContent.js) file.

In line# 106, change  `L(account.phoneNr + ' is online')` to below:
`L(account.phoneNr + ' is online at' + Date().toLocaleString().slice(3, 24))`

Save the file. Compile again using the steps given [here](https://github.com/LoranKloeze/WhatsAllApp#development).

Now, the log in the Chrome Console would have timestamps.

**Comment by nityoday** [comment]
@muskw I changed that line , and saved it , now for compiling , the steps written are :

```
Clone the repo git clone https://github.com/LoranKloeze/WhatsAllApp.git
Make sure Node.js is installed
Run npm install or yarn install
Run npx webpack or npx webpack --watch to pack the code from /src to /dist
Load the unpacked extension from /dist in Chrome
```
So yes, for that I installed Git and Git Hub , and was able to clone it in a different folder ( originally whatsallapp extension is in a different folder )

See the CMD lines 
```
Microsoft Windows [Version 10.0.17134.765]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\admin>cd C:\Users\admin\Documents\www

C:\Users\admin\Documents\www>git clone https://github.com/LoranKloeze/WhatsAllApp.git
fatal: destination path 'WhatsAllApp' already exists and is not an empty directory.

C:\Users\admin\Documents\www>git clone https://github.com/LoranKloeze/WhatsAllApp.git
fatal: destination path 'WhatsAllApp' already exists and is not an empty directory.

C:\Users\admin\Documents\www>git clone https://github.com/LoranKloeze/WhatsAllApp.git
Cloning into 'WhatsAllApp'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 447 (delta 10), reused 15 (delta 7), pack-reused 422
Receiving objects: 100% (447/447), 3.72 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (192/192), done.

C:\Users\admin\Documents\www>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\admin\Documents\www\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\admin\Documents\www\package.json'
npm WARN www No description
npm WARN www No repository field.
npm WARN www No README data
npm WARN www No license field.

up to date in 8.223s
found 0 vulnerabilities


C:\Users\admin\Documents\www>npx webpack
npx: installed 324 in 84.175s
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...

> webpack-cli@3.3.2 postinstall C:\Users\admin\Documents\www\node_modules\webpack-cli
> node ./bin/opencollective.js



                            Thanks for using Webpack!
                 Please consider donating to our Open Collective
                        to help us maintain this package.



                 Donate: https://opencollective.com/webpack/donate


npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\admin\Documents\www\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\admin\Documents\www\package.json'
npm WARN webpack-cli@3.3.2 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN www No description
npm WARN www No repository field.
npm WARN www No README data
npm WARN www No license field.

+ webpack-cli@3.3.2
added 208 packages from 127 contributors and audited 1053 packages in 136.984s
found 0 vulnerabilities

{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at runCommand.then (C:\Users\admin\AppData\Roaming\npm-cache\_npx\5900\node_modules\webpack\bin\webpack.js:143:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
```

Did I do right ?

**Comment by visika** [comment]
I managed to export the logs for further analysis, check it out

https://github.com/visika/WhatsAllApp/commit/6cf519d75db77b25712cc9d50cc49aeb4488cfbc
